# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=200)),
                ('win_date', models.DateTimeField(verbose_name=b'date published')),
            ],
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='user_name',
            new_name='user_id',
        ),
    ]
